name: mycourses
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^4.2.0
  google_fonts: ^6.2.1
  supabase_flutter: ^2.8.4
  device_info_plus: ^11.3.3
  pin_code_fields: ^8.0.1
  crypto: ^3.0.6
  flutter_localization: ^0.3.1
  animations: ^2.0.11
  page_transition: ^2.2.1
  auto_animated: ^3.2.0
  flutter_dotenv: ^5.2.1
  # Fix flutter_secure_storage to a compatible version
  flutter_secure_storage: ^9.2.4
  # Downgrade js to be compatible with flutter_secure_storage_web
  js: ^0.6.7  # Changed from ^0.7.2 to ^0.6.7 to be compatible with flutter_secure_storage
  # Downgrade freezed_annotation to be compatible with pod_player -> youtube_explode_dart
  freezed_annotation: ^2.4.1  # Changed from ^3.0.0 to ^2.4.1
  intl: ^0.19.0
  permission_handler_android: ^12.1.0
  material_color_utilities: ^0.11.1
  fake_async: ^1.3.2
  leak_tracker: ^10.0.8
  vm_service: ^14.3.1
  path_provider: ^2.1.5
  flutter_pdfview: ^1.4.0
  open_file: ^3.5.10
  # Video player dependencies
  video_player: ^2.9.3
  chewie: ^1.11.0
  image_picker: ^1.1.2
  http: ^1.3.0
  async: ^2.12.0
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.3.4
  webview_flutter_wkwebview: ^3.18.4
  url_launcher: ^6.3.1
  flutter_localizations:
    sdk: flutter
  # Windows-specific dependencies
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size
      ref: main
  win32: ^5.0.0
  path: ^1.9.1
  file_picker: ^9.2.1
  permission_handler: ^11.4.0
  share_plus: ^10.1.4
  shared_preferences: ^2.5.3
  
  # Video player libraries
  pod_player: ^0.2.2
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5
  media_kit_libs_android_video: ^1.3.6
  media_kit_libs_ios_video: ^1.1.4
  
  # UI enhancements
  wakelock_plus: ^1.2.10
  image_cropper: ^9.0.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300

  assets:
    - lib/presentation/screens/auth/
    - .env # إضافة ملف البيئة للأصول
    - assets/fonts/
